// Copyright (c) The OGX Contributors.
// All rights reserved.
//
// This source code is licensed under the terms described in the LICENSE file in
// the root directory of this source tree.
//
// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package ogxclient

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/ogx-ai/ogx-client-go/internal/apijson"
	"github.com/ogx-ai/ogx-client-go/internal/apiquery"
	"github.com/ogx-ai/ogx-client-go/internal/requestconfig"
	"github.com/ogx-ai/ogx-client-go/option"
	"github.com/ogx-ai/ogx-client-go/packages/pagination"
	"github.com/ogx-ai/ogx-client-go/packages/param"
	"github.com/ogx-ai/ogx-client-go/packages/respjson"
)

// OGX Inference API for generating completions, chat completions, and embeddings.
//
// This API provides the raw interface to the underlying models. Three kinds of
// models are supported:
//
//   - LLM models: these models generate "raw" and "chat" (conversational)
//     completions.
//   - Embedding models: these models generate embeddings to be used for semantic
//     search.
//   - Rerank models: these models reorder the documents based on their relevance to
//     a query.
//
// ChatCompletionMessageService contains methods and other services that help with
// interacting with the ogx-client API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewChatCompletionMessageService] method instead.
type ChatCompletionMessageService struct {
	Options []option.RequestOption
}

// NewChatCompletionMessageService generates a new service that applies the given
// options to each request. These options are applied after the parent client's
// options (if there is one), and before any request-specific options.
func NewChatCompletionMessageService(opts ...option.RequestOption) (r ChatCompletionMessageService) {
	r = ChatCompletionMessageService{}
	r.Options = opts
	return
}

// Get the messages in a stored chat completion.
func (r *ChatCompletionMessageService) List(ctx context.Context, completionID string, query ChatCompletionMessageListParams, opts ...option.RequestOption) (res *pagination.OpenAICursorPage[ChatCompletionMessageListResponse], err error) {
	var raw *http.Response
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	if completionID == "" {
		err = errors.New("missing required completion_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/chat/completions/%s/messages", completionID)
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// Get the messages in a stored chat completion.
func (r *ChatCompletionMessageService) ListAutoPaging(ctx context.Context, completionID string, query ChatCompletionMessageListParams, opts ...option.RequestOption) *pagination.OpenAICursorPageAutoPager[ChatCompletionMessageListResponse] {
	return pagination.NewOpenAICursorPageAutoPager(r.List(ctx, completionID, query, opts...))
}

// A message from a stored chat completion.
type ChatCompletionMessageListResponse struct {
	// The identifier of the chat message.
	ID string `json:"id" api:"required"`
	// The role of the message author.
	//
	// Any of "developer", "system", "user", "assistant", "tool".
	Role ChatCompletionMessageListResponseRole `json:"role" api:"required"`
	// Annotations for the message, when applicable.
	Annotations []map[string]any `json:"annotations" api:"nullable"`
	// Audio response data when using audio output modality.
	Audio map[string]any `json:"audio" api:"nullable"`
	// The text content of the message.
	Content string `json:"content" api:"nullable"`
	// Multipart content parts when the original message used content parts. Only text
	// and image_url parts.
	ContentParts []ChatCompletionMessageListResponseContentPartUnion `json:"content_parts" api:"nullable"`
	// Deprecated: the name and arguments of a function that should be called.
	FunctionCall ChatCompletionMessageListResponseFunctionCall `json:"function_call"`
	// The name of the message participant.
	Name string `json:"name" api:"nullable"`
	// The refusal message generated by the model, when applicable.
	Refusal string `json:"refusal" api:"nullable"`
	// For tool messages, the identifier of the tool call this message responds to.
	ToolCallID string `json:"tool_call_id" api:"nullable"`
	// The tool calls generated by the message, when applicable.
	ToolCalls []ChatCompletionMessageListResponseToolCallUnion `json:"tool_calls"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ID           respjson.Field
		Role         respjson.Field
		Annotations  respjson.Field
		Audio        respjson.Field
		Content      respjson.Field
		ContentParts respjson.Field
		FunctionCall respjson.Field
		Name         respjson.Field
		Refusal      respjson.Field
		ToolCallID   respjson.Field
		ToolCalls    respjson.Field
		ExtraFields  map[string]respjson.Field
		raw          string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponse) RawJSON() string { return r.JSON.raw }
func (r *ChatCompletionMessageListResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// The role of the message author.
type ChatCompletionMessageListResponseRole string

const (
	ChatCompletionMessageListResponseRoleDeveloper ChatCompletionMessageListResponseRole = "developer"
	ChatCompletionMessageListResponseRoleSystem    ChatCompletionMessageListResponseRole = "system"
	ChatCompletionMessageListResponseRoleUser      ChatCompletionMessageListResponseRole = "user"
	ChatCompletionMessageListResponseRoleAssistant ChatCompletionMessageListResponseRole = "assistant"
	ChatCompletionMessageListResponseRoleTool      ChatCompletionMessageListResponseRole = "tool"
)

// ChatCompletionMessageListResponseContentPartUnion contains all possible
// properties and values from
// [ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartTextParam],
// [ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParam].
//
// Use the methods beginning with 'As' to cast the union to one of its variants.
type ChatCompletionMessageListResponseContentPartUnion struct {
	// This field is from variant
	// [ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartTextParam].
	Text string `json:"text"`
	Type string `json:"type"`
	// This field is from variant
	// [ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParam].
	ImageURL ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParamImageURL `json:"image_url"`
	JSON     struct {
		Text     respjson.Field
		Type     respjson.Field
		ImageURL respjson.Field
		raw      string
	} `json:"-"`
}

func (u ChatCompletionMessageListResponseContentPartUnion) AsOpenAIChatCompletionContentPartTextParam() (v ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartTextParam) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ChatCompletionMessageListResponseContentPartUnion) AsOpenAIChatCompletionContentPartImageParam() (v ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParam) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

// Returns the unmodified JSON received from the API
func (u ChatCompletionMessageListResponseContentPartUnion) RawJSON() string { return u.JSON.raw }

func (r *ChatCompletionMessageListResponseContentPartUnion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Text content part for OpenAI-compatible chat completion messages.
type ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartTextParam struct {
	// The text content of the message.
	Text string `json:"text" api:"required"`
	// Must be 'text' to identify this as text content.
	//
	// Any of "text".
	Type string `json:"type"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Text        respjson.Field
		Type        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartTextParam) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartTextParam) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Image content part for OpenAI-compatible chat completion messages.
type ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParam struct {
	// Image URL specification and processing details.
	ImageURL ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParamImageURL `json:"image_url" api:"required"`
	// Must be 'image_url' to identify this as image content.
	//
	// Any of "image_url".
	Type string `json:"type"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ImageURL    respjson.Field
		Type        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParam) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParam) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Image URL specification and processing details.
type ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParamImageURL struct {
	// URL of the image to include in the message.
	URL string `json:"url" api:"required"`
	// Level of detail for image processing. Can be 'low', 'high', or 'auto'.
	//
	// Any of "low", "high", "auto".
	Detail string `json:"detail" api:"nullable"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		URL         respjson.Field
		Detail      respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParamImageURL) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseContentPartOpenAIChatCompletionContentPartImageParamImageURL) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Deprecated: the name and arguments of a function that should be called.
type ChatCompletionMessageListResponseFunctionCall struct {
	// Arguments to pass to the function as a JSON string.
	Arguments string `json:"arguments" api:"required"`
	// Name of the function to call.
	Name string `json:"name" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Arguments   respjson.Field
		Name        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseFunctionCall) RawJSON() string { return r.JSON.raw }
func (r *ChatCompletionMessageListResponseFunctionCall) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// ChatCompletionMessageListResponseToolCallUnion contains all possible properties
// and values from
// [ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCall],
// [ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCall].
//
// Use the methods beginning with 'As' to cast the union to one of its variants.
type ChatCompletionMessageListResponseToolCallUnion struct {
	ID string `json:"id"`
	// This field is from variant
	// [ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCall].
	Function ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCallFunction `json:"function"`
	Type     string                                                                         `json:"type"`
	// This field is from variant
	// [ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCall].
	Custom ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCallCustom `json:"custom"`
	JSON   struct {
		ID       respjson.Field
		Function respjson.Field
		Type     respjson.Field
		Custom   respjson.Field
		raw      string
	} `json:"-"`
}

func (u ChatCompletionMessageListResponseToolCallUnion) AsChatCompletionMessageToolCall() (v ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCall) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ChatCompletionMessageListResponseToolCallUnion) AsChatCompletionMessageCustomToolCall() (v ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCall) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

// Returns the unmodified JSON received from the API
func (u ChatCompletionMessageListResponseToolCallUnion) RawJSON() string { return u.JSON.raw }

func (r *ChatCompletionMessageListResponseToolCallUnion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Tool call specification for OpenAI-compatible chat completion responses.
type ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCall struct {
	// Unique identifier for the tool call.
	ID string `json:"id" api:"required"`
	// Function call details.
	Function ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCallFunction `json:"function" api:"required"`
	// Must be 'function' to identify this as a function call.
	//
	// Any of "function".
	Type string `json:"type" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ID          respjson.Field
		Function    respjson.Field
		Type        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCall) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCall) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Function call details.
type ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCallFunction struct {
	// Arguments to pass to the function as a JSON string.
	Arguments string `json:"arguments" api:"required"`
	// Name of the function to call.
	Name string `json:"name" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Arguments   respjson.Field
		Name        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCallFunction) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseToolCallChatCompletionMessageToolCallFunction) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// A call to a custom tool created by the model.
type ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCall struct {
	// The ID of the tool call.
	ID string `json:"id" api:"required"`
	// The custom tool that the model called.
	Custom ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCallCustom `json:"custom" api:"required"`
	// The type of the tool. Always 'custom'.
	//
	// Any of "custom".
	Type string `json:"type" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ID          respjson.Field
		Custom      respjson.Field
		Type        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCall) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCall) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// The custom tool that the model called.
type ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCallCustom struct {
	// The input for the custom tool call generated by the model.
	Input string `json:"input" api:"required"`
	// The name of the custom tool to call.
	Name string `json:"name" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Input       respjson.Field
		Name        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCallCustom) RawJSON() string {
	return r.JSON.raw
}
func (r *ChatCompletionMessageListResponseToolCallChatCompletionMessageCustomToolCallCustom) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ChatCompletionMessageListParams struct {
	// Identifier for the last message from the previous pagination request.
	After param.Opt[string] `query:"after,omitzero" json:"-"`
	// Number of messages to retrieve.
	Limit param.Opt[int64] `query:"limit,omitzero" json:"-"`
	// Sort order for messages by timestamp. Use "asc" or "desc". Defaults to "asc".
	//
	// Any of "asc", "desc".
	Order ChatCompletionMessageListParamsOrder `query:"order,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [ChatCompletionMessageListParams]'s query parameters as
// `url.Values`.
func (r ChatCompletionMessageListParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

// Sort order for messages by timestamp. Use "asc" or "desc". Defaults to "asc".
type ChatCompletionMessageListParamsOrder string

const (
	ChatCompletionMessageListParamsOrderAsc  ChatCompletionMessageListParamsOrder = "asc"
	ChatCompletionMessageListParamsOrderDesc ChatCompletionMessageListParamsOrder = "desc"
)
